"""Regenerate the checked-in spectrum coefficients using Python's standard library."""
import math
import re
from pathlib import Path

def i0(x):
    total = term = 1.0
    for k in range(1, 80):
        term *= (x / (2 * k)) ** 2
        total += term
        if term < total * 1e-16:
            break
    return total

def array(name, values):
    return f'static const float {name}[{len(values)}] = {{\n' + ''.join(
        '  ' + ', '.join(f'{v:.10e}f' for v in values[i:i+6]) + ',\n'
        for i in range(0, len(values), 6)) + '};\n'

header = Path(__file__).resolve().parents[1].joinpath('src/spectrum.h').read_text()
n = int(re.search(r'#define SPECTRUM_FFT_SIZE (\d+)u', header).group(1))
assert n >= 2 and n & (n - 1) == 0, 'FFT size must be a power of two'
beta = 8.6
fir = []
for i in range(127):
    x = i - 63
    sinc = 0.5 if x == 0 else math.sin(math.pi * x / 2) / (math.pi * x)
    if x != 0 and x % 2 == 0:
        sinc = 0.0
    fir.append(sinc * i0(beta * math.sqrt(1 - (x/63)**2)) / i0(beta))
s = sum(fir)
fir = [v/s for v in fir]
output = '// Generated by firmware/tools/generate_spectrum_tables.py; do not edit.\n'
output += array('spectrum_fir', fir)
output += array('spectrum_window', [0.5 - 0.5*math.cos(2*math.pi*i/n) for i in range(n)])
output += array('spectrum_cos', [math.cos(2*math.pi*i/n) for i in range(n//2)])
output += array('spectrum_sin', [-math.sin(2*math.pi*i/n) for i in range(n//2)])
output += array('spectrum_frequency', [20 * 1000**(i/255) for i in range(256)])
Path(__file__).resolve().parents[1].joinpath('src/spectrum_tables.h').write_text(output)
