M48
; DRILL file {KiCad 9.0.7} date 2026-03-06T23:58:07+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-06T23:58:07+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X5.1638Y-2.3366
X5.3913Y-2.3366
T2
X5.0787Y-5.7126
X5.8701Y-2.2165
T3
X5.3917Y-5.435
X5.3917Y-5.7106
M30
