M48
; DRILL file KiCad 10.0.1 date 2026-05-12T22:33:51
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-12T22:33:51+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X6.6421Y-2.0591
X6.8697Y-2.0591
T2
X6.4961Y-3.2598
X8.5787Y-1.9094
X8.6535Y-1.9094
X8.7283Y-1.9094
M30
