M48
; DRILL file KiCad 10.0.1 date 2026-05-13T00:08:48
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-13T00:08:48+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X4.8488Y-3.4311
X5.0764Y-3.4311
T2
X4.7028Y-4.6319
X6.9547Y-3.2776
M30
