foreach(required FIRMWARE_BIN FLASH_SIZE RESERVED_SIZE SRAM_SIZE WARNING_PERCENT)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} was not provided")
  endif()
endforeach()
if(NOT EXISTS "${FIRMWARE_BIN}")
  message(FATAL_ERROR "Firmware binary was not generated: ${FIRMWARE_BIN}")
endif()

if(DEFINED SIZE_OUTPUT_FILE)
  file(READ "${SIZE_OUTPUT_FILE}" section_table)
else()
  if(NOT DEFINED FIRMWARE_ELF OR NOT EXISTS "${FIRMWARE_ELF}")
    message(FATAL_ERROR "Firmware ELF was not generated: ${FIRMWARE_ELF}")
  endif()
  if(NOT DEFINED SIZE_TOOL)
    message(FATAL_ERROR "SIZE_TOOL was not provided")
  endif()
  execute_process(
    COMMAND "${SIZE_TOOL}" -A "${FIRMWARE_ELF}"
    RESULT_VARIABLE size_result
    OUTPUT_VARIABLE section_table
    ERROR_VARIABLE size_error
  )
  if(NOT size_result EQUAL 0)
    message(FATAL_ERROR "Unable to inspect firmware sections: ${size_error}")
  endif()
endif()

function(section_size section output)
  string(REPLACE "." "[.]" escaped "${section}")
  string(REGEX MATCH "(^|\n)${escaped}[ \t]+([0-9]+)" match "${section_table}")
  if(match)
    set(${output} "${CMAKE_MATCH_2}" PARENT_SCOPE)
  else()
    set(${output} 0 PARENT_SCOPE)
  endif()
endfunction()

function(format_percent numerator denominator output)
  math(EXPR tenths "${numerator} * 1000 / ${denominator}")
  math(EXPR whole "${tenths} / 10")
  math(EXPR fraction "${tenths} % 10")
  set(${output} "${whole}.${fraction}" PARENT_SCOPE)
endfunction()

file(SIZE "${FIRMWARE_BIN}" firmware_size)
math(EXPR firmware_capacity "${FLASH_SIZE} - ${RESERVED_SIZE}")
if(firmware_size GREATER firmware_capacity)
  message(FATAL_ERROR "Firmware uses ${firmware_size} bytes but only ${firmware_capacity} bytes are available")
endif()

foreach(section flashtext rodata binary_info flash_end ram_vector_table text data bss heap
                stack_dummy stack1_dummy scratch_x scratch_y)
  section_size(".${section}" ${section})
endforeach()
section_size(".ARM.exidx" arm_exidx)

math(EXPR flash_fixed "${flashtext} + ${rodata} + ${arm_exidx} + ${binary_info} + ${flash_end}")
math(EXPR flash_ram_code "${text}")
math(EXPR flash_data "${data}")
math(EXPR flash_other "${firmware_size} - ${flash_fixed} - ${flash_ram_code} - ${flash_data}")
if(flash_other LESS 0)
  set(flash_other 0)
endif()

math(EXPR scratch "${scratch_x} + ${scratch_y}")
math(EXPR static_sram "${ram_vector_table} + ${text} + ${data} + ${bss} + ${heap} +
                       ${stack_dummy} + ${stack1_dummy} + ${scratch}")
if(static_sram GREATER SRAM_SIZE)
  message(FATAL_ERROR "Static SRAM use is ${static_sram} bytes but capacity is ${SRAM_SIZE} bytes")
endif()
math(EXPR flash_free "${firmware_capacity} - ${firmware_size}")
math(EXPR sram_free "${SRAM_SIZE} - ${static_sram}")
math(EXPR flash_tenths "${firmware_size} * 1000 / ${firmware_capacity}")
math(EXPR sram_tenths "${static_sram} * 1000 / ${SRAM_SIZE}")
math(EXPR warning_tenths "${WARNING_PERCENT} * 10")
format_percent(${firmware_size} ${firmware_capacity} flash_percent)
format_percent(${flash_free} ${firmware_capacity} flash_free_percent)
format_percent(${static_sram} ${SRAM_SIZE} sram_percent)
format_percent(${sram_free} ${SRAM_SIZE} sram_free_percent)
math(EXPR firmware_kib_tenths "${firmware_size} * 10 / 1024")
math(EXPR firmware_kib_whole "${firmware_kib_tenths} / 10")
math(EXPR firmware_kib_fraction "${firmware_kib_tenths} % 10")

message(STATUS "")
message(STATUS "Pumper firmware resource report")
message(STATUS "  Binary: ${firmware_size} bytes (${firmware_kib_whole}.${firmware_kib_fraction} KiB)")
message(STATUS "  Flash: ${firmware_size}/${firmware_capacity} bytes usable (${flash_percent}% used, ${flash_free_percent}% free; ${flash_free} bytes free)")
message(STATUS "         capacity ${FLASH_SIZE}; settings reservation ${RESERVED_SIZE}")
message(STATUS "    resident code/metadata ${flash_fixed}; RAM code load ${flash_ram_code}; data load ${flash_data}; other ${flash_other}")
message(STATUS "  SRAM: ${static_sram}/${SRAM_SIZE} bytes (${sram_percent}% used, ${sram_free_percent}% free; ${sram_free} bytes free)")
message(STATUS "    vector table ${ram_vector_table}; RAM code ${text}; data ${data}; BSS ${bss}")
message(STATUS "    minimum heap ${heap}; core 0 stack ${stack_dummy}; core 1 stack ${stack1_dummy}; scratch ${scratch}")

if(flash_tenths GREATER_EQUAL warning_tenths)
  message(WARNING "Firmware flash use is ${flash_percent}% (warning threshold ${WARNING_PERCENT}%)")
endif()
if(sram_tenths GREATER_EQUAL warning_tenths)
  message(WARNING "Static SRAM use is ${sram_percent}% (warning threshold ${WARNING_PERCENT}%)")
endif()
