#ifndef USB_DESCRIPTORS_H_
#define USB_DESCRIPTORS_H_

#include "tusb.h"

enum {
  ITF_NUM_AUDIO_CONTROL = 0,
  ITF_NUM_AUDIO_STREAMING,
  ITF_NUM_HID,
  ITF_NUM_TOTAL
};

enum {
  STRID_LANGID = 0,
  STRID_MANUFACTURER,
  STRID_PRODUCT,
  STRID_SERIAL,
  STRID_AUDIO_IF,
  STRID_HID_IF,
};

// These IDs are part of the UAC2 control-request wire contract.
#define UAC2_ENTITY_CLOCK           0x04
#define UAC2_ENTITY_INPUT_TERMINAL  0x01
#define UAC2_ENTITY_FEATURE_UNIT    0x02
#define UAC2_ENTITY_OUTPUT_TERMINAL 0x03

#ifndef AUDIO_FUNC_HEADSET
#define AUDIO_FUNC_HEADSET 0x04
#endif
#ifndef AUDIO_TERM_TYPE_OUT_HEADPHONES
#define AUDIO_TERM_TYPE_OUT_HEADPHONES 0x0302
#endif

#define TUD_AUDIO_SPEAKER_STEREO_FB_DESC_LEN (TUD_AUDIO_DESC_IAD_LEN \
  + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + TUD_AUDIO_DESC_CLK_SRC_LEN \
  + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN \
  + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN + 3 * TUD_AUDIO_DESC_STD_AS_INT_LEN \
  + 2 * TUD_AUDIO_DESC_CS_AS_INT_LEN + 2 * TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN \
  + 2 * TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + 2 * TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN \
  + 2 * TUD_AUDIO_DESC_STD_AS_ISO_FB_EP_LEN)

// Alternate 1 is 16-bit PCM; alternate 2 is packed 24-bit PCM.
#define TUD_AUDIO_SPEAKER_STEREO_FB_DESCRIPTOR(_itfnum, _stridx, _epout, _epoutsize16, _epoutsize24, _epfb, _epfbsize) \
  TUD_AUDIO_DESC_IAD(_itfnum, 0x02, 0x00), \
  TUD_AUDIO_DESC_STD_AC(_itfnum, 0x00, _stridx), \
  TUD_AUDIO_DESC_CS_AC(0x0200, AUDIO_FUNC_HEADSET, TUD_AUDIO_DESC_CLK_SRC_LEN + TUD_AUDIO_DESC_INPUT_TERM_LEN + TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN, AUDIO_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
  TUD_AUDIO_DESC_CLK_SRC(UAC2_ENTITY_CLOCK, AUDIO_CLOCK_SOURCE_ATT_INT_PRO_CLK, AUDIO_CTRL_RW << AUDIO_CLOCK_SOURCE_CTRL_CLK_FRQ_POS, UAC2_ENTITY_INPUT_TERMINAL, 0x00), \
  TUD_AUDIO_DESC_INPUT_TERM(UAC2_ENTITY_INPUT_TERMINAL, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, UAC2_ENTITY_CLOCK, 0x02, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0x0000, 0x00), \
  TUD_AUDIO_DESC_OUTPUT_TERM(UAC2_ENTITY_OUTPUT_TERMINAL, AUDIO_TERM_TYPE_OUT_HEADPHONES, UAC2_ENTITY_INPUT_TERMINAL, UAC2_ENTITY_FEATURE_UNIT, UAC2_ENTITY_CLOCK, 0x0000, 0x00), \
  TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL(UAC2_ENTITY_FEATURE_UNIT, UAC2_ENTITY_INPUT_TERMINAL, AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO_CTRL_RW << AUDIO_FEATURE_UNIT_CTRL_VOLUME_POS, 0, 0, 0), \
  TUD_AUDIO_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), 0x00, 0x00, 0x00), \
  TUD_AUDIO_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), 0x01, 0x02, 0x00), \
  TUD_AUDIO_DESC_CS_AS_INT(UAC2_ENTITY_INPUT_TERMINAL, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, AUDIO_DATA_FORMAT_TYPE_I_PCM, 0x02, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00), \
  TUD_AUDIO_DESC_TYPE_I_FORMAT(2, 16), \
  TUD_AUDIO_DESC_STD_AS_ISO_EP(_epout, (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | TUSB_ISO_EP_ATT_DATA), _epoutsize16, 0x01), \
  TUD_AUDIO_DESC_CS_AS_ISO_EP(AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001), \
  TUD_AUDIO_DESC_STD_AS_ISO_FB_EP(_epfb, _epfbsize, TUD_OPT_HIGH_SPEED ? 4 : 1), \
  TUD_AUDIO_DESC_STD_AS_INT((uint8_t)((_itfnum) + 1), 0x02, 0x02, 0x00), \
  TUD_AUDIO_DESC_CS_AS_INT(UAC2_ENTITY_INPUT_TERMINAL, AUDIO_CTRL_NONE, AUDIO_FORMAT_TYPE_I, AUDIO_DATA_FORMAT_TYPE_I_PCM, 0x02, AUDIO_CHANNEL_CONFIG_NON_PREDEFINED, 0x00), \
  TUD_AUDIO_DESC_TYPE_I_FORMAT(3, 24), \
  TUD_AUDIO_DESC_STD_AS_ISO_EP(_epout, (uint8_t)(TUSB_XFER_ISOCHRONOUS | TUSB_ISO_EP_ATT_ASYNCHRONOUS | TUSB_ISO_EP_ATT_DATA), _epoutsize24, 0x01), \
  TUD_AUDIO_DESC_CS_AS_ISO_EP(AUDIO_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO_CTRL_NONE, AUDIO_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001), \
  TUD_AUDIO_DESC_STD_AS_ISO_FB_EP(_epfb, _epfbsize, TUD_OPT_HIGH_SPEED ? 4 : 1)

#endif
